name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cd libs 
        sudo make -j42069 
        cd .. 
        make -j42069 
        ls
        
